spring:
  application:
    name: forum-service
  #PostgreSQL by aiven.io
  datasource:
    url: jdbc:postgresql://cohort70-eddfish-eddfish.h.aivencloud.com:22423/defaultdb
    username: avnadmin
    password: ${AIVEN_PASS}
  #Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      uri: ${MONGODB_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true